// AUTO-GENERATED by scripts/discover_companies.py — do not edit manually.
// Last updated: 2026-04-28

import { Company, CompanyStage, ProblemDomain, TechCategory } from '../types'

// Suppress unused-import warnings when array is empty
void CompanyStage
void ProblemDomain
void TechCategory

export const discoveredCompanies: Company[] = []
